server:
  port: 8855
#spring:
 # datasource:
  #  url: jdbc:postgresql://localhost:5433/test
   # username: postgres
    #password: secret
    #driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui-custom.html
    operations-sorter: method
jwt:
  secret: mysecretkey
  expiration: 3600
