server:
  port: 8855
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./blog-app
  jpa:
    hibernate:
      ddl-auto: create
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui-custom.html
    operations-sorter: method
jasypt:
  encryptor:
    password: secret